---
kind: pipeline
name: amd64
platform:
  arch: amd64
steps:
- commands:
  - make test
  image: golangci/golangci-lint:v1.49.0
  name: test
  pull: always
  volumes:
  - name: cache
    path: /go
- commands:
  - licensed cache
  - licensed status
  image: public.ecr.aws/kanopy/licensed-go:3.7.3
  name: license-check
  volumes:
  - name: cache
    path: /go
- - depends_on:
    - test
    - license
    environment:
      GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    image: plugins/kaniko-ecr
    name: publish
    pull: always
    settings:
      build_args:
      - GIT_COMMIT
      no_push: true
      repo: ${DRONE_REPO_NAME}
      tags:
      - git-${DRONE_COMMIT_SHA:0:7}-amd64
      - latest-amd64
    volumes:
    - name: cache
      path: /go
    when:
      event:
      - pull_request
  - depends_on:
    - test
    - license
    environment:
      GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    image: plugins/kaniko-ecr
    name: publish
    pull: always
    settings:
      access_key:
        from_secret: ecr_access_key
      build_args:
      - GIT_COMMIT
      registry:
        from_secret: ecr_registry
      repo: ${DRONE_REPO_NAME}
      secret_key:
        from_secret: ecr_secret_key
      tags:
      - git-${DRONE_COMMIT_SHA:0:7}-amd64
      - latest-amd64
    volumes:
    - name: cache
      path: /go
    when:
      event:
      - push
  - depends_on:
    - test
    - license
    environment:
      GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
      VERSION: ${DRONE_TAG}-amd64
    image: plugins/kaniko-ecr
    name: publish
    pull: always
    settings:
      access_key:
        from_secret: ecr_access_key
      build_args:
      - GIT_COMMIT
      - VERSION
      registry:
        from_secret: ecr_registry
      repo: ${DRONE_REPO_NAME}
      secret_key:
        from_secret: ecr_secret_key
      tags:
      - git-${DRONE_COMMIT_SHA:0:7}-amd64
      - ${DRONE_TAG}-amd64
    volumes:
    - name: cache
      path: /go
    when:
      event:
      - tag
trigger:
  branch:
  - main
type: kubernetes
---
kind: pipeline
name: arm64
platform:
  arch: arm64
steps:
- commands:
  - make test
  image: golangci/golangci-lint:v1.49.0
  name: test
  pull: always
  volumes:
  - name: cache
    path: /go
- commands:
  - licensed cache
  - licensed status
  image: public.ecr.aws/kanopy/licensed-go:3.7.3
  name: license-check
  volumes:
  - name: cache
    path: /go
- - depends_on:
    - test
    - license
    environment:
      GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    image: plugins/kaniko-ecr
    name: publish
    pull: always
    settings:
      build_args:
      - GIT_COMMIT
      no_push: true
      repo: ${DRONE_REPO_NAME}
      tags:
      - git-${DRONE_COMMIT_SHA:0:7}-arm64
      - latest-arm64
    volumes:
    - name: cache
      path: /go
    when:
      event:
      - pull_request
  - depends_on:
    - test
    - license
    environment:
      GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
    image: plugins/kaniko-ecr
    name: publish
    pull: always
    settings:
      access_key:
        from_secret: ecr_access_key
      build_args:
      - GIT_COMMIT
      registry:
        from_secret: ecr_registry
      repo: ${DRONE_REPO_NAME}
      secret_key:
        from_secret: ecr_secret_key
      tags:
      - git-${DRONE_COMMIT_SHA:0:7}-arm64
      - latest-arm64
    volumes:
    - name: cache
      path: /go
    when:
      event:
      - push
  - depends_on:
    - test
    - license
    environment:
      GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
      VERSION: ${DRONE_TAG}-arm64
    image: plugins/kaniko-ecr
    name: publish
    pull: always
    settings:
      access_key:
        from_secret: ecr_access_key
      build_args:
      - GIT_COMMIT
      - VERSION
      registry:
        from_secret: ecr_registry
      repo: ${DRONE_REPO_NAME}
      secret_key:
        from_secret: ecr_secret_key
      tags:
      - git-${DRONE_COMMIT_SHA:0:7}-arm64
      - ${DRONE_TAG}-arm64
    volumes:
    - name: cache
      path: /go
    when:
      event:
      - tag
trigger:
  branch:
  - main
type: kubernetes
