---
kind: pipeline
name: amd64
platform:
  arch: amd64
resources:
  requests:
    cpu: 400
    memory: 2Gi
steps:
- commands:
  - make test
  image: golangci/golangci-lint:v1.49.0
  name: test
  pull: always
  volumes:
  - name: cache
    path: /go
- commands:
  - licensed cache
  - licensed status
  image: public.ecr.aws/kanopy/licensed-go:3.7.3
  name: license-check
  volumes:
  - name: cache
    path: /go
- depends_on:
  - test
  - license-check
  environment:
    GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
  image: plugins/kaniko-ecr
  name: publish
  pull: always
  settings:
    build_args:
    - GIT_COMMIT
    no_push: true
    repo: ${DRONE_REPO_NAME}
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}-amd64
    - latest-amd64
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - pull_request
trigger:
  branch:
  - main
type: kubernetes
volumes:
- name: cache
  path: /go
---
kind: pipeline
name: arm64
platform:
  arch: arm64
resources:
  requests:
    cpu: 400
    memory: 2Gi
steps:
- commands:
  - make test
  image: golangci/golangci-lint:v1.49.0
  name: test
  pull: always
  volumes:
  - name: cache
    path: /go
- commands:
  - licensed cache
  - licensed status
  image: public.ecr.aws/kanopy/licensed-go:3.7.3
  name: license-check
  volumes:
  - name: cache
    path: /go
- depends_on:
  - test
  - license-check
  environment:
    GIT_COMMIT: ${DRONE_COMMIT_SHA:0:7}
  image: plugins/kaniko-ecr
  name: publish
  pull: always
  settings:
    build_args:
    - GIT_COMMIT
    no_push: true
    repo: ${DRONE_REPO_NAME}
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}-arm64
    - latest-arm64
  volumes:
  - name: cache
    path: /go
  when:
    event:
    - pull_request
trigger:
  branch:
  - main
type: kubernetes
volumes:
- name: cache
  path: /go
