---
kind: pipeline
name: amd64
platform:
  arch: amd64
resources:
  requests:
    cpu: 400
    memory: 2Gi
steps:
- commands:
  - make test
  image: golangci/golangci-lint:v1.49.0
  name: test
  pull: always
  volumes:
  - name: cache
    path: /go
- commands:
  - licensed cache
  - licensed status
  image: public.ecr.aws/kanopy/licensed-go:3.7.3
  name: license-check
  volumes:
  - name: cache
    path: /go
trigger:
  branch:
  - main
type: kubernetes
volumes:
- name: cache
  path: /go
---
kind: pipeline
name: arm64
platform:
  arch: arm64
resources:
  requests:
    cpu: 400
    memory: 2Gi
steps:
- commands:
  - make test
  image: golangci/golangci-lint:v1.49.0
  name: test
  pull: always
  volumes:
  - name: cache
    path: /go
- commands:
  - licensed cache
  - licensed status
  image: public.ecr.aws/kanopy/licensed-go:3.7.3
  name: license-check
  volumes:
  - name: cache
    path: /go
trigger:
  branch:
  - main
type: kubernetes
volumes:
- name: cache
  path: /go
