---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hedgetrimmer
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulset
  - cronjobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hedgetrimmer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hedgetrimmer
subjects:
- kind: ServiceAccount
  name: hedgetrimmer
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hedgetrimmer
  namespace: devops
rules:
- apiGroups:
  - ""
  resources:
  - events
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - list
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hedgetrimmer
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hedgetrimmer
subjects:
- kind: ServiceAccount
  name: hedgetrimmer
  namespace: devops
